http://localhost:3005/workouts

###

POST http://localhost:3005/workouts HTTP/1.1
content-type: application/json

{
    "date": "2024-02-016T19:55:34.707Z"
}

###
DELETE http://localhost:3005/workouts/40bf HTTP/1.1

###
http://localhost:3005/exercises

###

POST http://localhost:3005/exercises HTTP/1.1
content-type: application/json

{
    "name": "Bench",
    "workoutId": "40bf"
}

###

PUT http://localhost:3005/exercises/6550 HTTP/1.1
content-type: application/json

{
    "name": "Bench 2",
    "workoutId": "40bf"
}

###
DELETE http://localhost:3005/exercises/ab81 HTTP/1.1

###
http://localhost:3005/sets?exerciseId=bcce